### PR TITLE
Support of boolean property check

### PR DESCRIPTION
**Pull request by gembeconsulting**
This PR supports boolean property matcher for iCanSee steps.
For that case, I introduced an additional type of check "is" to indicate that the property to check is boolean value.
i.e.: 

> I can see myControl with editable is 'true'

The stringify value is parsed using `JSON.parse(sValue)` in `utils.testTextValue()`.

### CODE REVIEW

**Comment by darksmo** [comment]
Hi @gembeconsulting, thanks for your contribution. We are going to have a look at it and merge in case. One first comment is on the berb 'is' wouldn't 'being' be more consistent with the other of the verbs?

**Comment by gembeconsulting** [comment]
Hey @darksmo, "being" suits very well in context of existing verbs, still indicating to expect a bool value.
However, I think I messed up this pull request. It contains to many changes (allowing empty string property check, allow "." for view name, new steps, various small adjustments...). I should have created separate branches.
I think it would be better to rework this pull request.

**Comment by darksmo** [comment]
Hi @gembeconsulting . I saw your change, and yes would be better to separate if possible. I suggest we start working on adding new steps, which I think brings the most value to the project. Then we can discuss or continue with the other changes in a separate pull request.

To help moving forward I have extracted the changes related to adding new steps in a clean diff (just the meaningful changes) and created the patch attached in  [add_new_steps.patch.zip](https://github.com/SAP/openui5-generic-app-testing/files/1705110/add_new_steps.patch.zip)
 .

So I would suggest we close this one and you send another pull request I can then give feedback on in a code review.

To proceed you could:
1. fork this repository on GitHub
2. unzip the content of [this attachment](https://github.com/SAP/openui5-generic-app-testing/files/1705110/add_new_steps.patch.zip) to obtain a `.patch` file
3. open git bash (or equivalent terminal)
4. `cd /tmp` (or any directory you can work in)
5. `git clone https://github.com/Gembe-Consulting/openui5-generic-app-testing.git`
6. `cd openui5-generic-app-testing`
7. `git apply /path/to/extracted/add_new_steps.patch`

At this point you should be in a state where if you do "git diff" you see what changes you would be sending. At this point you can either adjust something more or just go ahead and commit, push and create a new pull request we can discuss in GitHub.

Sounds good? If yes I'll close this pull request.

Best Regards,
Savio

**Comment by gembeconsulting** [comment]
Agreed, please close this PR.

Kind Regards,
Philipp

**Pull request closed without merging**
